/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmarPresencaRouteImport } from './routes/confirmar-presenca'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as MensagemRouteImport } from './routes/mensagem'
import { Route as PresentesRouteImport } from './routes/presentes'
import { Route as RecadinhosRouteImport } from './routes/recadinhos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarPresencaRoute = ConfirmarPresencaRouteImport.update({
  id: '/confirmar-presenca',
  path: '/confirmar-presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagemRoute = MensagemRouteImport.update({
  id: '/mensagem',
  path: '/mensagem',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentesRoute = PresentesRouteImport.update({
  id: '/presentes',
  path: '/presentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecadinhosRoute = RecadinhosRouteImport.update({
  id: '/recadinhos',
  path: '/recadinhos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmar-presenca': typeof ConfirmarPresencaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/mensagem': typeof MensagemRoute
  '/presentes': typeof PresentesRoute
  '/recadinhos': typeof RecadinhosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmar-presenca': typeof ConfirmarPresencaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/mensagem': typeof MensagemRoute
  '/presentes': typeof PresentesRoute
  '/recadinhos': typeof RecadinhosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmar-presenca': typeof ConfirmarPresencaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/mensagem': typeof MensagemRoute
  '/presentes': typeof PresentesRoute
  '/recadinhos': typeof RecadinhosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmar-presenca'
    | '/localizacao'
    | '/mensagem'
    | '/presentes'
    | '/recadinhos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmar-presenca'
    | '/localizacao'
    | '/mensagem'
    | '/presentes'
    | '/recadinhos'
  id:
    | '__root__'
    | '/'
    | '/confirmar-presenca'
    | '/localizacao'
    | '/mensagem'
    | '/presentes'
    | '/recadinhos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmarPresencaRoute: typeof ConfirmarPresencaRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  MensagemRoute: typeof MensagemRoute
  PresentesRoute: typeof PresentesRoute
  RecadinhosRoute: typeof RecadinhosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-presenca': {
      id: '/confirmar-presenca'
      path: '/confirmar-presenca'
      fullPath: '/confirmar-presenca'
      preLoaderRoute: typeof ConfirmarPresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagem': {
      id: '/mensagem'
      path: '/mensagem'
      fullPath: '/mensagem'
      preLoaderRoute: typeof MensagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentes': {
      id: '/presentes'
      path: '/presentes'
      fullPath: '/presentes'
      preLoaderRoute: typeof PresentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recadinhos': {
      id: '/recadinhos'
      path: '/recadinhos'
      fullPath: '/recadinhos'
      preLoaderRoute: typeof RecadinhosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmarPresencaRoute: ConfirmarPresencaRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  MensagemRoute: MensagemRoute,
  PresentesRoute: PresentesRoute,
  RecadinhosRoute: RecadinhosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
